apiVersion: v1
kind: Service
metadata:
  name: gitops-app-service
  namespace: default
spec:
  selector:
    app: gitops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
